Added has_password funtion in utils folder
opencodeiiita/SaveMyForm-Backend pull request #13
Opened 2022-12-17 20:54 UTC by Aman1143

Issue: 10

#### Short description of what this resolves:
I just install bcryptjs module . Taking password from user as a req.body and hash it.

![hash_password](https://user-images.githubusercontent.com/100416012/208265645-eaebb418-2f20-4240-809d-f2b29601ab2c.png)

2022-12-17 21:13 UTC, BuddyLongLegs requested changes
`password` instead of being extracted from body, should the and only argument of the function, return the hashPassword (replace hasPassword with hashPassword) string. Also i guess 12 is your encryption key (salt), set an enviornment variable `SECRET` to 12 and use process.env['SECRET'] instead of 12 in the hash function.

2022-12-18 04:57 UTC, Aman1143 commented
ok

2022-12-18 05:48 UTC, Aman1143 commented
I have changed that you want .
![hash_password1](https://user-images.githubusercontent.com/100416012/208283589-81c58b76-1f13-4f23-a363-85c119bcfb5e.png)

2022-12-18 05:59 UTC, BuddyLongLegs requested changes
Use `process.env.SECRET` (i.e., enviornment variable should be `SECRET`). Also just return the hashPassword (replace hasPassword with hashPassword). Returning password=hashPassword will cause an issue.

2022-12-18 06:38 UTC, BuddyLongLegs requested changes
Do not make hash_password the default export. Just put `export hash_password;`. Sorry for not mentioning this change earlier.

2022-12-18 06:38 UTC, Aman1143 commented
make change
![hash_password2](https://user-images.githubusercontent.com/100416012/208285028-91ce58ac-7876-4b4c-9fbf-4c3395238f93.png)

2022-12-18 08:31 UTC, BuddyLongLegs commented on utils/password.js
> +export default hash_password;
make it `export hash_password;`

2022-12-18 08:52 UTC, Aman1143 commented
I remove default that you want .

2022-12-18 11:12 UTC, BuddyLongLegs approved these changes
Great Work!

2022-12-18 11:12 UTC, merged