Issue 123
opencodeiiita/SaveMyForm-Backend pull request #137
Opened 2023-06-04 06:03 UTC by chandra1899

Issue: 123

Resolved merge conflicts 
added controller to update collaborators

2023-06-04 06:33 UTC, BuddyLongLegs requested changes

2023-06-04 06:33 UTC, BuddyLongLegs commented on controllers/project.controller.js
>      if (req.body.collaborators) {
remove these collaborator checks, they are no more required here

2023-06-05 05:50 UTC, chandra1899 commented
i removed unwanted checks you can review it now

2023-06-09 04:32 UTC, BuddyLongLegs approved these changes

2023-06-09 04:32 UTC, merged