Add update project controller
opencodeiiita/SaveMyForm-Backend pull request #82
Opened 2023-01-01 15:24 UTC by Im-Madhur-Gupta

Issue: 77

#### Changes proposed in this pull request and/or Screenshots of changes:

- Adds controller function to update a project

2023-01-01 15:33 UTC, BuddyLongLegs requested changes
Generate the response data by using inbuilt mongoose functions like `populate`, `select`, etc.

2023-01-02 09:25 UTC, Im-Madhur-Gupta commented
@BuddyLongLegs I have added mongoose query string to build the response data object.

2023-01-02 16:37 UTC, Im-Madhur-Gupta commented
@BuddyLongLegs I have made the changes.

2023-01-02 16:54 UTC, BuddyLongLegs approved these changes

2023-01-02 16:54 UTC, merged